---
# tasks file for ansible-role_sops

- name: Ensure target OS is suitable
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version | int >= 7
    fail_msg: "Playbook only suitable for distro {{ ansible_os_family }} major version {{ ansible_distribution_major_version }}"
    success_msg: "Ok we're good"
- name: Ensure dest dir exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/sops/age/
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
- name: Ensure age/sops keys file is installed
  ansible.builtin.template:
    src: user/.config/sops/age/{{ item }}.j2
    dest: /home/{{ user }}/.config/sops/age/{{ item }}
    mode: "0400"
    owner: "{{ owner }}"
    group: "{{ group }}"
  loop:
    - keys.txt
- name: Ensure sops config yaml file is installed (op zich niet secret, maar doe maar 0400)
  ansible.builtin.template:
    src: user/{{ item }}.j2
    dest: /home/{{ user }}/{{ item }}
    mode: "0400"
    owner: "{{ owner }}"
    group: "{{ group }}"
  loop:
    - .sops.yaml
- name: Ensure Secrets OPerationS (SOPS) is installed
  ansible.builtin.yum:
    name: "{{ item }}"
    disable_gpg_check: true
  loop:
    - https://github.com/getsops/sops/releases/download/v3.8.1/sops-3.8.1.x86_64.rpm

- name: Debug
  ansible.builtin.debug:
    msg: "Running on {{ ansible_hostname }}"
