---
# tasks file for ansible-role_sops

- name: Ensure dest dir exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/sops/age/
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "0755"
- name: Ensure age/sops keys file is installed
  ansible.builtin.template:
    src: user/.config/sops/age/{{ item }}.j2
    dest: /home/{{ user }}/.config/sops/age/{{ item }}
    mode: "0400"
    owner: "{{ owner }}"
    group: "{{ group }}"
  loop:
    - keys.txt
- name: Ensure sops config yaml file is installed (op zich niet secret, maar doe maar 0400)
  ansible.builtin.template:
    src: user/{{ item }}.j2
    dest: /home/{{ user }}/{{ item }}
    mode: "0400"
    owner: "{{ owner }}"
    group: "{{ group }}"
  loop:
    - .sops.yaml
# https://api.github.com/repos/mozilla/sops/releases/latest
- name: Ensure Secrets OPerationS (SOPS) is installed (for RedHat OS family)
  ansible.builtin.yum:
    name: "{{ item }}"
    disable_gpg_check: true
  loop:
    - https://github.com/getsops/sops/releases/download/v3.8.1/sops-3.8.1.x86_64.rpm
  when: ansible_os_family == 'RedHat'
- name: Ensure Secrets OPerationS (SOPS) is installed (for Debian OS family)
  ansible.builtin.apt:
    deb: "{{ item }}"
    # disable_gpg_check: true
  loop:
    - https://github.com/getsops/sops/releases/download/v3.8.1/sops_3.8.1_amd64.deb
  when: ansible_os_family == 'Debian'

- name: Debug
  ansible.builtin.debug:
    msg: "Running on {{ ansible_hostname }}"
